version: "3.8"
services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "5001:5000" 
    networks:
      - clinica-net
    volumes:
      # Nginx
      - ./data/nginx/protected_routes.conf:/etc/nginx/protected_routes.conf
      - ./data/nginx/protected_routes.json:/etc/nginx/protected_routes.json
      # Logs
      - ./data/logs/nginx:/var/log/nginx
      - ./data/logs/fail2ban/fail2ban-actions.log:/var/log/fail2ban-actions.log
      - ./data/logs/certs.log:/var/log/certs.log
      # SSL
      - ./data/ssl:/etc/ssl/server
      # NAXSI
      - ./data/naxsi/generated.wl:/etc/nginx/generated.wl
      - ./data/naxsi/naxsi.rules:/etc/nginx/naxsi.rules
    cap_add:
      - NET_ADMIN

  openemr:
    image: openemr/openemr:latest
    networks:
      - clinica-net
    volumes:
      - openemr-data:/var/www/localhost/htdocs/openemr
    environment:
      - MYSQL_HOST=db-openemr
      - MYSQL_USER=openemr
      - MYSQL_PASSWORD=openemr
      - MYSQL_DATABASE=openemr
    depends_on:
      - db-openemr

  db-openemr:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=senhasegura
      - MYSQL_DATABASE=openemr
      - MYSQL_USER=openemr
      - MYSQL_PASSWORD=openemr
    volumes:
      - db-openemr-data:/var/lib/mysql
    networks:
      - clinica-net

volumes:
  openemr-data:
  db-openemr-data:

networks:
  clinica-net:
    driver: bridge