version: "3.8"
services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "5001:5000" 
    networks:
      - clinica-net
    volumes:
      - ./data/protected_routes.conf:/etc/nginx/protected_routes.conf
      - ./data/protected_routes.json:/etc/nginx/protected_routes.json
      - ./data/nginx:/var/log/nginx
      - ./data/fail2ban/logs/fail2ban-actions.log:/var/log/fail2ban-actions.log
      - ./data/ssl:/etc/ssl/server
      - ./data/certs.log:/var/log/certs.log
    cap_add:
      - NET_ADMIN

  sistema:
    build: ../sistema-clinica/
    expose:
      - "5000"
    networks:
      - clinica-net

networks:
  clinica-net:
    driver: bridge